# contents of properties file
db.prefix = mongodb+srv://
db.user = sn1153
db.pwd = gBAPoyMKCx4Uyldr
db.dbName = MediaForumDatabase
db.dbUrl = @mediaforum.0pu6g.mongodb.net/
db.params = ?retryWrites=true&w=majority&appName=MediaForum
